### ISSUE TITLE
Painting process slows down

### ISSUE THREAD

**Issue by takeny1998** [AutoPipo/pypipo#14]
Painting process slows down comared to previous commit(baa115db25ed7958543018ac10c9812d36bcdd38)
* its processing time increased by nearly 400% (from 15 seconds to 60 seconds)

i founded difference from `upstream/main`, which is that argument `d` in `bilateralFilter`  was changed to `-1` (it calculated the d value based on the image size previously)
* as far as i know, it means that the `bilateralFilter` calculates `d`(distance between neighboring pixels) automatically with `sigmaSpace`.
* i think that argument `d` caluated too small than proper value (d represents filters kernel size, so the smaller it is, the longer the processing time)

so, i think **we need to restore prevoius way**, what about your thoughts? (baa115db25ed7958543018ac10c9812d36bcdd38 : calculating `d` based on the image size)

**Comment by Minku-Koo** [comment]
_Oh, that is goood point._

I think, some document said -1 is adapted radius, so I modified parameter.

But your feedback is so reasonable.

**Can you test about now and before?**

I know the before operation is
```
# qimg : input image
# step : blurring step 0 to 5 (step 5 is more blur then step 0)
radius += min( int(int((qimg.shape[1] * qimg.shape[0]) ** 0.5) // 100 * 1.5) , 40) + step * 2
```

I think that operation is so complicated, so you can present me new operation.

Thank you for your help :)

**Comment by takeny1998** [comment]
sure, here is the result what i tested before:
* I tested before and now total 3 times
* the runtime environment is MacBook pro(M1 Max 64GB)

BEFORE Operation:

**Comment by Minku-Koo** [comment]
OK

Can u test and suggest me adapted value of sigma space?

I think
new operation : (image height * image width) ** 0.5 // 20 -> this can do same process

Thank you :)

**Comment by takeny1998** [comment]
actually, idk what does operation you suggested mean. 

BUT, I can suggest proper radius range. I tested using the `lalaland.png` below:

![lalaland](https://github.com/AutoPipo/pypipo/assets/89298198/1a323911-8cc6-4323-ab98-07d4e53d0b26)

### Maximum Value
![image](https://github.com/AutoPipo/pypipo/assets/89298198/84ca08bb-9a6c-42cd-97ee-3ef73bf50607)

here is the graph that plots proceed time against parameter d. (0 ~ 255)
* the time complexity of the `bilateral filter` is `O(n^2)`, So as the `d` goes up, the `proceed_time` is steadily increasing.
* you can see that the slope is increasing rapidly, especially for `d` up to 50.

![blurring_51](https://github.com/AutoPipo/pypipo/assets/89298198/cbe178e8-f566-49b0-b353-78db48057d6f)
* This is the blurred result with `d=51`

![blurring_251](https://github.com/AutoPipo/pypipo/assets/89298198/8b2a6669-a08b-45d4-bfbd-d7cb836dbce1)
* This is the blurred result with `d=251`
* Despite the more **than 10x difference in execution time**, the results are **not significant**.

**SO, I think that maximum value of `d` should be `50`.** 

### Minimum Value
![out](https://github.com/AutoPipo/pypipo/assets/89298198/69ab7964-7de1-4566-9be7-32c1e13ea18a)

I tested again to get proper minimum value with same environment, and I compiled all the results into a GIF.

**in my opinion, `d` should be at least 23 to cluster color properly.**

if you have different opinion or need the detailed information, such as differential graph, please contact me :)

**Comment by takeny1998** [comment]
if we defined the ratio of proper `d` and image pixels, we can always find proper value regardless of image size.

here is the ratio based on `lalaland.png`'s proper `d=23`
`d = num_of_pixel * 0.00002495660`

and we can normalize the value of `d` to moderate proper value. (0 ~ 0.00005316840(maximum))

I'ii try it out soon, and send a PR.

**Comment by Minku-Koo** [comment]
Thank you for your help.
I merge to dev branch, and maybe later your changes will be merge to main.
Thank you again, for your contributions.
